version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ORDERS_ENDPOINT=http://backend:8080/orders
  backend:
    image: lurifn/fdm-backend
    ports:
      - "8081:8080"
    env_file:
      - configs/backend.env
