---
apiVersion: v1
kind: Secret
metadata:
  name: example-backend-secret
type: Opaque
data:
  # run "echo 'YOUR_SECRET_HERE' | base64" in your cmd to get this value
  noreply-email-password: ZXhhbXBsZQ==
